AWSTemplateFormatVersion: 2010-09-09
Description: |

Parameters:

Resources:
  ObjectStorageReplicationPolicy:
  Type: AWS::IAM::RolePolicy
  Properties:
    PolicyDocument:
      Statement:
        - Action:
            - s3:GetReplicationConfiguration
            - s3:List*
            - s3:CreateAccessPoint
            - s3:AbortMultipartUpload
            - s3:*
          Effect: Allow
          Resource: !Sub arn:${AWS::Partition}:s3:::${AppName}-${AWS::Region}-${AWS::AccountId}
        - Action:
            - s3:GetObjectVersionForReplication
            - s3:GetObjectVersionAcl
            - s3:GetObjectVersionTagging
          Effect: Allow
          Resource: !Sub arn:${AWS::Partition}:s3:::${AppName}-${AWS::Region}-${AWS::AccountId}/*
        - Action:
            - s3:ReplicateObject
            - s3:ReplicateDelete
            - s3:ReplicationTags
          Effect: Allow
          Resource: !Sub arn:${AWS::Partition}:s3:::${AppName}-replicas-${AWS::Region}-${AWS::AccountId}/*
      Version: "2012-10-17"
    PolicyName: bucket-replication-policy
    RoleName: !Ref ObjectStorageReplicationRole
Outputs:
